### ISSUE TITLE
Questions about implementation

### ISSUE THREAD

**Issue by qwer1304** [amber0309/SCA#1]
Hi,
Thx for a great implementation!

I have some questions about it compared to the paper:
File SCA_quantities.m:

Line 99:
I assume this implements calcultion of Ps (equation (13) in the paper).
Why there's no multiplication by nk?

Line 106 and onwards:
I assume this implements calculation of Qs (equation (14) in the paper).
The implementation looks very different from the equation.
Could you please explain?

Line 118 and onwards:
I assume D equals K\*L\*K in the paper (equation (20)).
The implementation looks very different from that.
Could you please explain?

Also, Algorithm 1 in the paper tells to **first** center the kernel at step 2 and **then** solve for B* in step 3. It follows, that D would need to be calculated with a **centered** kernel. But the code doesn't look like doing so (line 126).

Demo files, e.g. demo_2a_2a.m:
Line 69:
Why are the kernels centered with H? 
In the paper, the **only** place where such centering is applied is in calculation of Qs in equation (14).
Please explain.

Thank you,
David

**Comment by amber0309** [comment]
> Line 99: I assume this implements calcultion of Ps (equation (13) in the paper). Why there's no multiplication by nk?

The loop on line 97 is over all valid points instead of classes.

> Line 106 and onwards: I assume this implements calculation of Qs (equation (14) in the paper). The implementation looks very different from the equation. Could you please explain?

The implementation is based on the definition of within-class scatter ( the equation after equation (10) ). Specifically, we first sum the distances between point of the same class and the center of that class (Q_i*Q_i'). Then we sum the distances computed from different classes (Q = Q + Q_i*Q_i').

> Line 118 and onwards: I assume D equals K*L*K in the paper (equation (20)). The implementation looks very different from that. Could you please explain?

Yes, you are right. The implementation is again based on the definition (equation (7)). In the first loop, we compute the over of all domains. In the second, we sum the distance of each domain to the overall mean.

> Also, Algorithm 1 in the paper tells to first center the kernel at step 2 and then solve for B* in step 3. It follows, that D would need to be calculated with a centered kernel. But the code doesn't look like doing so (line 126).

It would need to be centered when using the formulation in the paper. However, we calculate D directly follow its definition.

> Demo files, e.g. demo_2a_2a.m: Line 69: Why are the kernels centered with H? In the paper, the only place where such centering is applied is in calculation of Qs in equation (14). Please explain.

You are right that in the paper the kernel involving the target data is not centered. We did so since we found it would yield better results on some data sets. Thanks a lot for pointing out this!
